# Generated by Django 6.0.8 on 2026-10-05 15:38

import django.db.models.deletion
import modules.core.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('payment_terms', models.CharField(blank=True, default='', help_text='e.g. Net 30, COD, 2/10 Net 30. Free text: terms are agreed, not configured.', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], db_index=True, default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'status'], name='idx_supplier_org_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'name'), name='uniq_supplier_org_name')],
            },
            managers=[
                ('objects', modules.core.managers.SoftDeleteManager()),
                ('all_objects', modules.core.managers.AllObjectsManager()),
            ],
        ),
    ]
