# Generated by Django 6.0.8

import django.core.validators
import django.db.models.deletion
import modules.core.managers
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0002_purchaseorder_purchaseorderline_and_more"),
        ("catalog", "0003_alter_product_managers"),
        ("branches", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="quantity_received",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Cumulative quantity posted through goods received notes.",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("number", models.CharField(db_index=True, max_length=32)),
                (
                    "delivery_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Supplier delivery / reference number.",
                        max_length=64,
                    ),
                ),
                ("received_date", models.DateField()),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_received_notes",
                        to="branches.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_received_notes",
                        to="organizations.organization",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="purchasing.purchaseorder",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_received_notes",
                        to="purchasing.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
            managers=[
                ("objects", modules.core.managers.SoftDeleteManager()),
                ("all_objects", modules.core.managers.AllObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name="GoodsReceivedLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ordered_quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("previously_received", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("batch_number", models.CharField(blank=True, default="", max_length=64)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchasing.goodsreceivednote",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_received_lines",
                        to="catalog.product",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="purchasing.purchaseorderline",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="goodsreceivednote",
            constraint=models.UniqueConstraint(
                fields=("organization", "number"), name="uniq_grn_org_number"
            ),
        ),
        migrations.AddIndex(
            model_name="goodsreceivednote",
            index=models.Index(fields=["organization", "status"], name="idx_grn_org_status"),
        ),
        migrations.AddIndex(
            model_name="goodsreceivednote",
            index=models.Index(fields=["purchase_order", "status"], name="idx_grn_po_status"),
        ),
        migrations.AddIndex(
            model_name="goodsreceivednote",
            index=models.Index(fields=["branch", "status"], name="idx_grn_branch_status"),
        ),
        migrations.AddConstraint(
            model_name="goodsreceivedline",
            constraint=models.UniqueConstraint(
                fields=("grn", "purchase_order_line"), name="uniq_grn_line_po_line"
            ),
        ),
    ]
