# Generated by Django 6.0.8

import django.db.models.deletion
import modules.core.managers
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("branches", "0001_initial"),
        ("catalog", "0003_alter_product_managers"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="branches.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_stocks",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_stocks",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["branch__name", "product__name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("OPENING_BALANCE", "Opening balance"),
                            ("PURCHASE_RECEIPT", "Purchase receipt"),
                            ("SALE", "Sale"),
                            ("RETURN", "Return"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("TRANSFER_IN", "Transfer in"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("DAMAGE", "Damage"),
                            ("STOCK_COUNT", "Stock count"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("reference_type", models.CharField(blank=True, default="", max_length=32)),
                (
                    "reference_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("quantity_before", models.DecimalField(decimal_places=3, max_digits=12)),
                ("quantity_after", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="branches.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_movements",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("number", models.CharField(db_index=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("DISPATCHED", "Dispatched"),
                            ("IN_TRANSIT", "In transit"),
                            ("RECEIVED", "Received"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="branches.branch",
                    ),
                ),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_dispatched",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transfers",
                        to="organizations.organization",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
            managers=[
                ("objects", modules.core.managers.SoftDeleteManager()),
                ("all_objects", modules.core.managers.AllObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name="StockTransferLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "approved_quantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
                ),
                (
                    "dispatched_quantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
                ),
                (
                    "received_quantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_lines",
                        to="catalog.product",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stocktransfer",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="branchstock",
            constraint=models.UniqueConstraint(
                fields=("branch", "product"), name="uniq_branch_stock_branch_product"
            ),
        ),
        migrations.AddIndex(
            model_name="branchstock",
            index=models.Index(fields=["organization", "product"], name="idx_bstock_org_product"),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(fields=["organization", "created_at"], name="idx_imov_org_created"),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(fields=["branch", "created_at"], name="idx_imov_branch_created"),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(fields=["product", "created_at"], name="idx_imov_product_created"),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["reference_type", "reference_id"], name="idx_imov_reference"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.UniqueConstraint(
                fields=("organization", "number"), name="uniq_transfer_org_number"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["organization", "status"], name="idx_trf_org_status"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["source_branch", "status"], name="idx_trf_src_status"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["destination_branch", "status"], name="idx_trf_dst_status"),
        ),
        migrations.AddConstraint(
            model_name="stocktransferline",
            constraint=models.UniqueConstraint(
                fields=("transfer", "product"), name="uniq_transfer_line_product"
            ),
        ),
    ]
